//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC5Application.Models
{
   using System;
   using System.Collections.Generic;
   using System.ComponentModel.DataAnnotations;
   public partial class 客戶聯絡人
   {
      public int Id { get; set; }
      [Required]
      public int 客戶Id { get; set; }
      [Required]
      public string 職稱 { get; set; }
      [Required]
      public string 姓名 { get; set; }
      [Required]
      [RegularExpression( @"(@)(.+)$")]
      public string Email { get; set; }
      [Required]
      [RegularExpression(@"\d{4}-\d{6}")]
      public string 手機 { get; set; }
      [Required]
      public string 電話 { get; set; }
      public bool IsDelete { get; set; }

      public virtual 客戶資料 客戶資料 { get; set; }
   }
}
